### ISSUE TITLE
full API implementation

### ISSUE THREAD

**Issue by thr3lk** [justinthrelkeld/pinboard-api#4]
Implement the full API as [documented by Pinboard](https://pinboard.in/api):
- [x] /posts/all
- [x] /posts/add
- [x] /posts/delete
- [x] /posts/recent
- [x] /tags/get - issue #8
- [ ] /posts/suggest - issue #7
- [x] /posts/update
- [ ] /posts/get - issue #5
- [ ] /posts/dates - issue #6 
- [ ] /tags/delete - issue #9 
- [ ] /tags/rename - issue #10
- [ ] /notes/list - issue #12 
- [ ] /notes/\<hash\> - issue #13 
- [ ] /user/secret - issue #11 
- [x] /user/api_token
